site_name: nexosim

repo_url: https://github.com/asynchronics/nexosim-py/

nav:
  - index.md
  - User Guide: user_guide.md
  - Reference:
      - "nexosim": reference/mod_root.md
      - "nexosim.aio": reference/mod_aio.md
      - "nexosim.exceptions": reference/mod_exceptions.md
      - "nexosim.time": reference/mod_time.md
      - "nexosim.types": reference/mod_types.md

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            members_order: source

  - include-markdown
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details

watch:
  - src
